### ISSUE TITLE
Library does not support TC74 temperature component

### ISSUE THREAD

**Issue by garrettheath4** [adafruit/Adafruit_CircuitPython_PCT2075#13]
The README states that this library works for both the PCT2075 and the TC74 temperature sensor component. But I've found that it only works for the PCT2075. Not only is the TC74 using a different I2C address (which is not a big deal since this library lets you pass the I2C address as a constructor argument) but the way that the data and configuration are laid out in the two devices are completely different and incompatible.

For example, the PCT2075 stores the temperature reading as an 11-bit number where the unit is 0.125 degrees C each _but_ the TC74 simply stores the temperature reading as an 8-bit byte number where the unit is 1 degrees C each.

I [forked this library](https://github.com/garrettheath4/Adafruit_CircuitPython_PCT2075) and created a [`tc74-support` branch](https://github.com/garrettheath4/Adafruit_CircuitPython_PCT2075/tree/TC74-support) in my version of the repo with the intent of generalizing the code so it can support both the PCT2075 and the TC74 temperature sensors and then submitting a pull request to this Adafruit library. But I've found that the logic is too different between the two, as I said. But feel free to check out my changes. 🙂 

As an end user, I think it would be weird to have to install a PCT2075-specific Adafruit library in order to use my TC74. What do you suggest we do?

- Should my TC74 library code be added as a new, separate Adafruit repository/library, named "Adafruit_CircuitPython_TC74" instead of "Adafruit_CircuitPython_PCT2075"?
- Should the name of this Adafruit library be generalized to something like "Adafruit_CircuitPython_Temperature_I2C" that contains both a PCT2075 and a TC74 Python class?
- Should we just ignore this and add my TC74 class to the Adafruit repository/library (assuming you like it)?

**Comment by tannewt** [comment]
@garrettheath4 Thanks for the questions! My preference would be the first option, a separate repo for the different driver. I can either make it and you can PR, or you can make a repo and we'll fork it back into adafruit. Thanks!

@siddacious Heads up. Arduino may have the same problem. (I saw you added the note about the TC74 to this README.)

**Comment by garrettheath4** [comment]
@tannewt Thanks! I agree that would be more clear to end users. As long as Adafruit isn't worried about having too many single-purpose repos, haha.

**Comment by garrettheath4** [comment]
@tannewt I created a new repo `Adafruit_CircuitPython_TC74` based on this repo. Could you please fork it into the Adafruit universe? https://github.com/garrettheath4/Adafruit_CircuitPython_TC74

**Comment by garrettheath4** [comment]
@tannewt Thanks (to you and/or Adafruit) for forking my repo! I see that [_adafruit/Adafruit_CircuitPython_TC74_](https://github.com/adafruit/Adafruit_CircuitPython_TC74) is now live. But it doesn't seem to have Issues enabled (otherwise I would be posting this message there). And its Actions either aren't enabled or they haven't been pulled from the configuration files in `.github/workflows` in that repo because I don't see any Actions listed for the repo and its code definitely isn't being published to PyPI. Could you please enable Actions, PyPI publishing, and Issues for that repo? Thanks!

**Comment by tannewt** [comment]
I always forget that forks have issues off by default. I've enabled them and invited you as a collaborator.
