### ISSUE TITLE
Add TC74 i2c temperature sensor library

### ISSUE THREAD

**Issue by iayanpahwa** [adafruit/Adafruit_CircuitPython_PCT2075#4]
TC74 from microchip is a cheap and good i2c based temperature sensor, will be good to have a supported library in CircuitPython

**Comment by ladyada** [comment]
ok moved this to PCT repo

**Comment by iayanpahwa** [comment]
Thanks @siddacious

**Comment by kattni** [comment]
@iayanpahwa Are you still interested in adding TC74 functionality to this library, or do you consider this issue resolved?

**Comment by iayanpahwa** [comment]
@kattni hey, sorry I didn't get time to work on this one. Now I don't have a TC74 handy to check the changes. I think you can close this issue if you want.

**Comment by ladyada** [comment]
kk! if someone has the same issue they can raise it, with the stuff that isnt working
